version: "3.7"
services:
  airflow-webserver:
    build: ./
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ../../genaidrivenetl:/opt/airflow/genaidrivenetl  # твой код
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    depends_on:
      - airflow-postgres
      - airflow-scheduler

  airflow-scheduler:
    build: ./
    volumes:
      - ../../genaidrivenetl:/opt/airflow/genaidrivenetl
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    depends_on:
      - airflow-postgres

  airflow-postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"